#!/bin/bash

# while-menu: a menu-driven system information program
RESPONDER_CONF="/etc/fdresponder/fdresponder.properties"
DEPLOY_RULES="/etc/fdresponder/deploy_rules.conf"
FGFMSD_LOG="/var/log/fgfmsd.log"
FDRESPONDER_LOG="/opt/fortinet/forticloud/fdresponder.log"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    return
}

function help() {
    echo "ipaddr                                    Configure ip addr."
    echo "set default <fmg-ip> <fmg-sn>             Configure default FortiManager ip addr and SN."
    echo "set option <fmg-ip> <fgt-sn> <group-id>   Configure FortiGate SN and FortiManager ip addr."
    echo "exit                                      Exit the CLI."
}

function config_ip() {
    IP=$(ip addr | grep global | cut -d' ' -f 6 | cut -d'/' -f 1)
    sed -i -e '/fdmgrsvr/cfdmgrsvr='$IP':541    # the IP address of forticloud responder tool/' $RESPONDER_CONF
    cat $RESPONDER_CONF | grep fdmgrsvr
    systemctl restart fdresponder
    systemctl restart fgfmsd
}

while true; do

    read -p "#" key sub para1 para2 para3

    case "$key" in
        "?")
            help
            continue
            ;;
        "ipaddr")
            nmtui
            config_ip
            continue
            ;;
        "exit")
            exit 0
            continue
            ;;
        "set")
            case "$sub" in
                "default")
                    if [[ $para1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
                        if [[ $para2 =~ ^[A-Z0-9]{16}$ ]]; then
                            echo ""
                        else
                            echo "SN Format Invalid"
                        fi
                    else
                        echo "IP Format Invalid"
                    fi
                    ;;
                "option")
                    if [[ $para1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
                        if [[ $para2 =~ ^[A-Z0-9]{16}$ ]]; then
                            echo ""
                        else
                            echo "SN Format Invalid"
                        fi
                    else
                        echo "IP Format Invalid"
                    fi
                    ;;
                *)
                    echo "Unknown action"
                    ;;
            esac
            continue
            ;;
        "")
            continue
            ;;
        *)
            echo "Usage: {ipaddr|set default|set option|exit}"
            continue
            ;;
    esac
done