#!/bin/bash

# while-menu: a menu-driven system information program
RESPONDER_CONF="/etc/fdresponder/fdresponder.properties"
DEPLOY_RULES="/etc/fdresponder/deploy_rules.conf"
FGFMSD_LOG="/var/log/fgfmsd.log"
FDRESPONDER_LOG="/opt/fortinet/forticloud/fdresponder.log"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    return
}

function help() {
    echo "ipaddr                                    Configure ip addr."
    echo "set default <fmg-ip>-<fmg-sn>             Configure default FortiManager ip addr and SN."
    echo "set <fgt-sn> <fmg-ip>-<fmg-sn>            Configure FortiGate SN and FortiManager ip addr, SN."
    echo "set <fgt-sn>-<fgt-backup-sn> <fmg-ip>-<fmg-sn> <ha-group> <ha-passwd> <ha-mode> <intf1>,<port1>,<intf2>,<port2>   Configure FortiGate SN and FortiManager ip addr, SN For HA."
    echo "delete <fgt-sn>                           Delete FortiManager IP Entry base on SN."
    echo "password                                  Change Password For Admin."
    echo "show                                      Show Configuration."
    echo "exit                                      Exit the CLI."
}

function config_ip() {
    IP=$(ip addr | grep "global eno" | cut -d' ' -f 6 | cut -d'/' -f 1)
    sed -i -e '/fdmgrsvr/cfdmgrsvr='$IP':541    # the IP address of forticloud responder tool' $RESPONDER_CONF
    systemctl restart fdresponder
    systemctl restart fgfmsd
}

while true; do

    read -p "#" key para1 para2 para3 para4 para5 para6 

    case "$key" in
        "?")
            help
            continue
            ;;
        "ipaddr")
            nmtui
            config_ip
            continue
            ;;
        "exit")
            exit 0
            continue
            ;;
        "set")
            case "$para1" in
                "default")
                    IP=$(echo $para2 | cut -f1 -d-)
                    SN=$(echo $para2 | cut -f2 -d-)
                    if [[ $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
                        if [[ $SN =~ ^[A-Z0-9]{16}$ ]]; then
                            sed -i -e '/default_fmg_ip/cdefault_fmg_ip='$IP'   # the IP address of external FortiManager server (default FMG)' $RESPONDER_CONF
                            sed -i -e '/default_fmg_sn/cdefault_fmg_sn='$SN'   # the SN of external FortiManager server (default FMG SN)' $RESPONDER_CONF
                            systemctl restart fgfmsd
                        else
                            echo "SN Format Invalid"
                        fi
                    else
                        echo "IP Format Invalid"
                    fi
                    ;;
                *)
                    if [[ $para1 =~ ^[A-Z0-9]{16}$ ]]; then
                        # todo: replace old config 
                        # sed -i 's/^$para1/$para1 $para2/' $DEPLOY_RULES || echo $para1 $para2 >> $DEPLOY_RULES
                        systemctl restart fgfmsd
                    else
                        if [[ $para1 =~ ^[A-Z0-9]{16}-[A-Z0-9]{16}$ ]]; then
                            # todo: replace old config 
                            # sed -i -e '/'$para1'/c'$para1' '$para2' '$para3' '$para4' '$para5' '$para6'' $DEPLOY_RULES || echo $para1 $para2 $para3 $para4 $para5 $para6 >> $DEPLOY_RULES
                            systemctl restart fgfmsd
                        else
                            echo "set <fgt-sn> | <fgt-sn>-<fgt-backup-sn>"
                        fi
                    fi
            esac
            continue
            ;;
        "show")
            echo "External FortiManager Server Configuration: "
            cat $RESPONDER_CONF
            echo "===================================="
            echo "FortiManager IP Address base on SN: "
            cat $DEPLOY_RULES
            continue
            ;;
        "delete")
            if [[ $para1 =~ ^[A-Z0-9]{16}$ ]]; then
                sed -i '/'$para1'/ d' $DEPLOY_RULES
                systemctl restart fgfmsd
            else
                if [[ $para1 =~ ^[A-Z0-9]{16}-[A-Z0-9]{16}$ ]]; then
                    sed -i '/'$para1'/ d' $DEPLOY_RULES
                    systemctl restart fgfmsd
                else
                    echo "SN Format Invalid"
                fi
            fi
            continue
            ;;
        "password")
            passwd admin
            continue
            ;;
        "")
            continue
            ;;
        *)
            echo "Usage: {ipaddr|set default|set|delete|password|show|exit}"
            continue
            ;;
    esac
done